version: '3'
services:
  serv_x:
    image: image_x
    volumes:
    - type: bind
      source: mydata
      target: /data
    container_name: cont_x
    build:
      context: .
      dockerfile: app1.dockerfile
      args:
        - ENV_VAR0=python:alpine
    environment:
      - DEBUG=true
    

